
/*
	GENERATED BY:
  	generate-app-entry.js
	DO NOT EDIT MANUALLY
*/

/* Import every component in src/components */
import AlertPopUp from './components/AlertPopUp/AlertPopUp.vue';
import Checkbox from './components/Checkbox/Checkbox.vue';
import Input from './components/Input/Input.vue';
import NavBar from './components/NavBar/NavBar.vue';
import PopUp from './components/PopUp/PopUp.vue';
import SearchForm from './components/SearchForm/SearchForm.vue';
import SideBar from './components/SideBar/SideBar.vue';
import Table from './components/Table/Table.vue';

/* Export components individually */
export { AlertPopUp, Checkbox, Input, NavBar, PopUp, SearchForm, SideBar, Table };

/* Use every component when the library is installed as a Vue plugin */
function install(Vue) {
	Vue.component('AlertPopUp', AlertPopUp);
	Vue.component('Checkbox', Checkbox);
	Vue.component('Input', Input);
	Vue.component('NavBar', NavBar);
	Vue.component('PopUp', PopUp);
	Vue.component('SearchForm', SearchForm);
	Vue.component('SideBar', SideBar);
	Vue.component('Table', Table);
}

/* Export the library as a plugin */
export default { install: install };
